### ISSUE TITLE
How does one connect to the FireTV to run this script?

### ISSUE THREAD

**Issue by jim16127** [esc0rtd3w/firestick-loader#1]
When opening the 'root-stick.cmd' there is no prompt to adb connect to the device. I have manually opened a command prompt and connected successfully but the script does not recognize that I'm connected to the device via adb. Is there something i'm missing? I've been trying to figure this thing out for quite some time now to no avail. :(

**Comment by esc0rtd3w** [comment]
there are 2 adb options on firetv, and you use usb-a to usb-a connector. i have only tested script on firestick btw

**Comment by jim16127** [comment]
Plugging the FireTV stick into the USB port and adb connecting is the only option? You say USB a to USB a. With a fire stick would USB a to USB micro straight from stick not work? Either way wifi is not an option?
