### ISSUE TITLE
clarify function of..

### ISSUE THREAD

**Issue by unbender** [esc0rtd3w/firestick-loader#2]
Would you please clarify the function of:

com.amazon.application.compatibility.enforcer

com.amazon.tv.launcher/.content.ComradeReceiver

com.amazon.kso.blackbird

com.amazon.dcp.contracts.framework.library
com.amazon.dcp.contracts.library

I plan to use my FTV stick for prime movies, netflix, hbo now, TheBlaze TV, along with kodi.  I have disabled

package:com.amazon.precog
package:com.amazon.videoads.app
package:com.amazon.device.software.ota
package:com.amazon.kso.blackbird
package:com.amazon.application.compatibility.enforcer
package:com.amazon.device.software.ota.override
package:com.amazon.application.compatibility.enforcer.sdk.library
com.amazon.tv.settings/com.amazon.tv.settings.tv.AppDisableService
com.amazon.tv.launcher/.ads.AdRefreshReceiver

which is likely why attempting to disable com.amazon.settings.systemupdates/.OTAEventReceiver  resulted in an error.

**Comment by esc0rtd3w** [comment]
i have not tested Amazon Prime with disabled or removed Amazon Bloat. If you are using the current scripting to remove system apps, you can install Amazon Underground and Amazon Video apps (currently testing) to use Prime, i think
