### ISSUE TITLE
Any hope for Fire Stick 4K?

### ISSUE THREAD

**Issue by cscaloni** [esc0rtd3w/firestick-loader#3]
I would like to root my fire stick 4k:

Software version: Fire OS 6.2.6.5 (NS6265/2157)
Init fire tv version: 6.1.7.0-713

Any hope for this type of devices?

Thanks you very much for your work and patience

**Comment by esc0rtd3w** [comment]
i do not have one of these devices yet to test.

as far as rooting, i probably won't add debloat and other support until a public rooting method is available.
