### ISSUE TITLE
breaks 5.2.7.2 leaves it on amazon logo or black screen.

### ISSUE THREAD

**Issue by niceguy167** [esc0rtd3w/firestick-loader#4]
Ran on a fresh 5.2.7.2 Stock w/Magisk. 
Gives lots of errors during remove of apps and process also give lots of errors through the entire script when it is running the tank full :) 
I can recover my stick and get back to factory :) 
If you have any ideas that would be awesome as I think this project would be super super helpful. 
Thanks again for your hard work :)

Also just looking over the script 
%shell% "rm -r /system/priv-app/ContentSupportProvider/"
%shell% "rm -r /system/priv-app/CrashManager/"
%shell% "rm -r /system/priv-app/ConnectivityDiag/"
%shell% "rm -r /system/priv-app/DeviceClientPlatformContractsFrame
this stuff is not located here on my stick. 
I ran recovery mode and adp shelled in :) 
Found it 
Mine is located in 
cd /data/data/apps located here

**Comment by esc0rtd3w** [comment]
i should probably update the readme with better instructions, but here is the process I take

TWRP is a REQUIREMENT

1) Have 5.2.7.2 installed for Tank

2) Make sure ADB confirmations are done for  connection to PC and I also setup Mouse Toggle at this point, and verify working.

3) You can now run the "setup-tank-full.cmd" script and it will force reboot to recovery

4) The script will check your OS version and model, then you choose NO "N" for downgrade option to 5.2.6.3

* You must follow instructions and press ENTER after system mounting in TWRP *

5) The script will do all of the steps, starting by debloating apps, then it will push apk's, scripts for SH Script Runner and Titanium backup files to /system. Last, it will (re)install Magisk and fix permissions.

6) After completed, follow instructions to restore Titanium Backup files for ATV Launcher and SH Script runner Data only

7) Reboot

The ATV Launcher is the default launcher and will be installed to /system as part of the process. If you are getting a blank screen or stuck on boot animation , then you have no Home Menu installed, i assume.

Those Amazon apps in /data/app/ are removed and /data/app/ should not contain any Amazon apps after completed. I may have to add to scripting to remove others that get updated from system apps.

**Comment by esc0rtd3w** [comment]
> 
> Also just looking over the script
> %shell% "rm -r /system/priv-app/ContentSupportProvider/"
> %shell% "rm -r /system/priv-app/CrashManager/"
> %shell% "rm -r /system/priv-app/ConnectivityDiag/"
> %shell% "rm -r /system/priv-app/DeviceClientPlatformContractsFrame
> this stuff is not located here on my stick.
> I ran recovery mode and adp shelled in :)
> Found it
> Mine is located in
> cd /data/data/apps located here

if you could (or i can later), load fresh 5.2.7.2 stock w/magisk and let it update all the system apps, then use "adb shell ls /data/app/" to see what apps were updated, as i have added some already

%shell% "rm -r /data/app/com.amazon.aca-1/"
%shell% "rm -r /data/app/com.amazon.alexashopping-1/"
%shell% "rm -r /data/app/com.amazon.amazonvideo.livingroom.firetv-1/"
%shell% "rm -r /data/app/com.amazon.aria-1/"
%shell% "rm -r /data/app/com.amazon.avl.ftv-1/"
%shell% "rm -r /data/app/com.amazon.avod-1/"
%shell% "rm -r /data/app/com.amazon.bueller.music-1/"
%shell% "rm -r /data/app/com.amazon.cardinal-1/"
%shell% "rm -r /data/app/com.amazon.firebat-1/"
%shell% "rm -r /data/app/com.amazon.ftv.glorialist-1/"
%shell% "rm -r /data/app/com.amazon.hedwig-1/"
%shell% "rm -r /data/app/com.amazon.katoch-1/"
%shell% "rm -r /data/app/com.amazon.kso.blackbird-1/"
%shell% "rm -r /data/app/com.amazon.shoptv.client-1/"
%shell% "rm -r /data/app/com.amazon.tahoe-1/"
%shell% "rm -r /data/app/com.amazon.tv.devicecontrolsettings-1/"
%shell% "rm -r /data/app/com.amazon.tv.launcher-1/"
%shell% "rm -r /data/app/com.amazon.tv.livetv-1/"
%shell% "rm -r /data/app/com.amazon.tv.ottssocompanionapp-1/"
%shell% "rm -r /data/app/com.amazon.tv.releasenotes-1/"
%shell% "rm -r /data/app/com.amazon.venezia-1/"

and the -2 variants

**Comment by Ziggy815** [comment]
Hi there, 
first of all, i love your work! I just have one question : Is it possible to remove almost anything from amazon except the alexa app ?  I Have the latest firetv stick (2nd version 2k) and would love to get rid of all the crap that i dont need but keep alexa to control and search.

Greetings
Zig.

**Comment by esc0rtd3w** [comment]
yeah, you can keep any app you want, but be aware that some have dependencies on other apps. So for example, if you remove a package, it might start a kernel spam of errors. After removal, reboot and wipe cache, then check logcat and you should see basically no fast scrolling activity, except on initial launch of logcat, on a fresh debloat with a network connection.

The basic idea was to debloat it as far as possible and not break settings. Then from there, if replacements can be made for common things like WiFi, Bluetooth, etc, then many more apps can be removed without needing the Amazon Settings dependency. The System Monitor was commented and left alone (but can be removed [/system/priv-app/SystemStatusMonitor/] and [/system/priv-app/SystemStatusMonitorSys])  so you can check your CPU/GPU, Memory, etc after debloating or for testing, to make sure no memory or CPU spikes.

The alexa app is listed under debloat scripts and setup-full-tank and setup-full-montoya scripts.

here are some examples to keep

::%shell% "rm -r /system/priv-app/com.amazon.alexashopping/"

:: Alexa Voice Layer
::%shell% "rm -r /system/priv-app/com.amazon.avl.firetv/"

:: Fire TV Alexa Alerts
::%shell% "rm -r /system/priv-app/com.amazon.tv.alexaalerts/"

:: Amazon Voice Support
::%shell% "rm -r /system/priv-app/com.amazon.vizzini/"

:: VoiceView
::%shell% "rm -r /system/priv-app/logan/"

**Comment by esc0rtd3w** [comment]
issue has been resolved, and adb confirmation now working after debloat, so apps like Mouse Toggle can be loaded after debloat or before, it no longer matters.
