### ISSUE TITLE
setup-tank-full.cmd NOT WORKING

### ISSUE THREAD

**Issue by sharpiemomo** [esc0rtd3w/firestick-loader#6]
I Have a Fire Stick 2nd Gen (Tank) And I am unable to downgrade it or flash it with this software. Is there any other way to downgrade the fire stick or restore it to stock ROM?

**Comment by esc0rtd3w** [comment]
You think I spend all this time making that script and it don't work?

First, you need TWRP installed. Without it, the script will boot you to stock recovery.

I have actually recently added the amonet batch files for windows users.

Once you have done the hardware wire trick and install TWRP, run the script and it will work. It supports 5.2.6.3 and 5.2.7.2.

5.2.7.2 recommended and to already have the oobe completed, ie wifi, account, etc setup.
